version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm test

  publish:
    docker:
      - image: circleci/node:8.12
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish
      
workflows:
  version: 2
  tagged-build:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/